parameters:
    database_host: us-cdbr-iron-east-04.cleardb.net
    database_port: null
    database_name: heroku_270dfe8a30a67bb
    database_user: be4c44ae923a9f
    database_password: 9914edc5
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
